object Version {
  val logback             = "1.1.7"
  val scalaLogging        = "3.4.0"
  val config              = "1.3.0"
  val akka                = "2.4.9"
  val scalaTest           = "3.0.0"
  val scalaCheck          = "1.13.2"
  val elasticsearch       = "2.2.2"
  val jts                 = "1.13"
  val scale               = "0.0.2"
  val async               = "0.9.6-RC2"
  val metrics             = "3.1.2"
  val influxdbReporter    = "0.7.0"
  val metricsScala        = "3.5.2"
  val mfglabs             = "0.10.0"
}
